### ISSUE TITLE
[Bug] Step 2 not working because npm can't install a package

### ISSUE THREAD

**Issue by fingers53** [skills/test-with-actions#17]
On step 2 of the process, I cannot get the test to pass. The error I get is: 

npm ERR! 404 Not Found - GET https://registry.npmjs.org/remark-present-link-consistent - Not found

![image](https://user-images.githubusercontent.com/54557739/203838191-24f195e4-620d-4672-8a5c-eba6b77c3527.png)

**Comment by k-byun** [comment]
I get the same exact error.  README.md lacks some clarity from the beginning of Step 2.

**Comment by xuhongl** [comment]
same error

**Comment by heiskr** [comment]
Hello, are you folks creating these on a personal account, or organizational account? Are you still seeing this error?

**Comment by gsacavdm** [comment]
@fingers53 , you have a typo on your first line, it's preset, not prese**n**t (you have an extra N there).

**Comment by heiskr** [comment]
Ah, dreaded typos. 😬 If anyone has ideas on how we can make this course easier, we're very open to it.
