### ISSUE TITLE
Step 3 - Uploading what artifact?

### ISSUE THREAD

**Issue by adriandersen** [skills/test-with-actions#35]
### Summary

actions/upload-artifact does not know what artifact to upload in Step 3

### How to reproduce

1. Edit ci.yml as explained in `Step 3: Upload test reports`
2. Run action
3. Get Warning `No files were found with the provided path: public/. No artifacts will be uploaded`
![image](https://github.com/skills/test-with-actions/assets/31202534/281155d6-f4f9-4660-84fb-804c0b8f7205)

### Additional context

This might be an error on my end, but the guide seems to be missing a step about how to upload the output of the markdown linter, as if `actions/upload-artifact` will automagically detect output from the previous step (which does not seem to be the case)

**Comment by sinsukehlab** [comment]
I have the same question.

**Comment by sinsukehlab** [comment]
GitHub Copilot Chat advised me to add a reporter to the linting step because the `remark` linter doesn't generate a report file by default.
