### ISSUE TITLE
[Bug] Step 4 workflow is not working

### ISSUE THREAD

**Issue by mumincacao** [skills/test-with-actions#58]
### Summary

Workflow `.github/workflows/4-add-branch-protections.yml` is not working.

### How to reproduce

1. Create or edit branch protection setting
2. `Merge changes from origin main into ci` step failure

![image](https://github.com/skills/test-with-actions/assets/77599269/ec84753b-cb0e-4fdc-bbe7-89c209e3eb00)

### Additional context

It's seem `.github/script/merge-branch.sh` has not executable permission.

**Comment by sinsukehlab** [comment]
Sorry for introducing the bug. I did make the script executable, but I forgot the token in the workflow file.
